### ISSUE TITLE
关于许可证问题

### ISSUE THREAD

**Issue by mukuss** [RT-Thread-packages/gui_engine#62]
LGPL许可证允许在使用动态链接时不公开产品代码。
但使用在RTT系统只能静态链接，LGPL退化为GPL。
就是说我的产品代码必须公开才可以使用，不知道我理解的是否正确。
我认为这是不合理的，商业代码大多不可能开源，请问应对这种问题的方式只有放弃gui_engine么？

**Comment by iamyhw** [comment]
LGPL是GPL的变种，也是GNU为了得到更多的甚至是商用软件开发商的支持而提出的。与GPL的最大不同是，可以私有使用LGPL授权的自由软件，开发出来的新软件可以是私有的而不需要是自由软件。
gui_engine可以自由使用,柿饼UI和你自己的代码则可以归版权方私有.

**Comment by mukuss** [comment]
谢谢你的回答，还有一个疑问：我把gui_engine包含进新软件后无需公开我软件的源码是么？
